version: '2'
services:
    fourchetteippon-app:
        image: fourchetteippon
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fourchetteippon-postgresql:5432/fourchetteIppon
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fourchetteippon-postgresql:
        extends:
            file: postgresql.yml
            service: fourchetteippon-postgresql
